name: PR Review on Comment

on:
  issue_comment:
    types: [created]

jobs:
  # Job to handle the '/approve' command
  approve:
    name: Approve PR
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/approve') &&
      github.event.comment.user.login == github.event.issue.user.login
    runs-on: ubuntu-latest
    steps:
      - name: Approve Pull Request
        env:
          GH_TOKEN: ${{ secrets.APPROVER_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          APPROVAL_MESSAGE: "Approved automatically by @PriestyBot based on a command from the PR author @${{ github.event.comment.user.login }}."
        run: |
          gh pr review $PR_NUMBER --approve --body "$APPROVAL_MESSAGE" -R $GITHUB_REPOSITORY

  # Job to handle the '/request-changes' command
  request_changes:
    name: Request Changes on PR
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/request-changes') &&
      github.event.comment.user.login == github.event.issue.user.login
    runs-on: ubuntu-latest
    steps:
      - name: Extract Comment Body
        id: get_comment
        # This strips the command prefix and saves the rest of the comment
        run: echo "body=$(echo '${{ github.event.comment.body }}' | sed 's/\/request-changes//' | xargs)" >> $GITHUB_OUTPUT
      - name: Request Changes on Pull Request
        env:
          GH_TOKEN: ${{ secrets.APPROVER_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          # Use the extracted comment as the reason for the change request
          COMMENT_BODY: ${{ steps.get_comment.outputs.body }}
        run: |
          gh pr review $PR_NUMBER --request-changes --body "$COMMENT_BODY" -R $GITHUB_REPOSITORY

  # Job to handle the '/comment' command
  comment:
    name: Comment on PR
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/comment') &&
      github.event.comment.user.login == github.event.issue.user.login
    runs-on: ubuntu-latest
    steps:
      - name: Extract Comment Body
        id: get_comment
        run: echo "body=$(echo '${{ github.event.comment.body }}' | sed 's/\/comment//' | xargs)" >> $GITHUB_OUTPUT
      - name: Post Review Comment
        env:
          GH_TOKEN: ${{ secrets.APPROVER_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          COMMENT_BODY: ${{ steps.get_comment.outputs.body }}
        run: |
          gh pr review $PR_NUMBER --comment --body "$COMMENT_BODY" -R $GITHUB_REPOSITORY