name: Approve on PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  approve_from_comment:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/approve') &&
      github.event.comment.user.login == github.event.issue.user.login
    runs-on: ubuntu-latest

    steps:
      - name: Approve Pull Request
        env:
          # This token comes from your PriestyBot account
          GH_TOKEN: ${{ secrets.APPROVER_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          APPROVAL_MESSAGE: "Approved automatically by @PriestyBot based on a command from the PR author @${{ github.event.comment.user.login }}."
        run: |
          gh pr review $PR_NUMBER --approve --body "$APPROVAL_MESSAGE" -R $GITHUB_REPOSITORY