name: Bot Help Comment

on:
  # This workflow triggers when a reviewer is requested on a pull request
  pull_request:
    types: [review_requested]

jobs:
  post_help_comment:
    # This 'if' condition is crucial. It makes sure the job only runs
    # when the requested reviewer's username is exactly 'PriestyBot'.
    if: github.event.requested_reviewer.login == 'PriestyBot'
    runs-on: ubuntu-latest
    
    steps:
      - name: Post Command List Comment
        env:
          # We use the bot's token so the comment comes from PriestyBot itself
          GH_TOKEN: ${{ secrets.APPROVER_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          gh pr comment $PR_NUMBER -R $GITHUB_REPOSITORY --body "
          Hello! I'm PriestyBot, your automated PR assistant. 👋

          Since you've requested my review, you (as the PR author) can now use the following commands by posting a new comment:

          *   \` /approve \`
              > Approves the pull request.

          *   \` /request-changes <message> \`
              > Requests changes on the PR, using your message as the reason.
              > *Example: `/request-changes I need to add more tests for this.`*

          *   \` /comment <message> \`
              > Submits your message as a formal review comment.
              > *Example: `/comment This looks good, but let's monitor performance.`*
          "