# .github/workflows/strict-review.yml
name: In-Depth Code Review

on:
  pull_request:
    types: [labeled]

jobs:
  run-strict-review:
    if: github.event.label.name == 'bot: in-depth review'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      checks: write

    steps:
      - name: Acknowledge In-Depth Review
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Alright, time for a deep dive! I'm running the full suite of strict linters (\`black\`, \`isort\`, \`flake8\`) now. I'll post the results as a review in just a moment. 🕵️‍♂️"
        env: { GH_TOKEN: "${{ secrets.APPROVER_TOKEN }}", GH_REPO: "${{ github.repository }}" }

      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Linters and Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - run: pip install black isort flake8

      - name: Run Linters with Reviewdog
        id: strict_lint
        continue-on-error: true
        run: |
          (isort --check-only . && black --check . && flake8 .) | reviewdog -name="In-Depth Code Quality" -reporter=github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.APPROVER_TOKEN }}
      
      - name: Post Final Report
        run: |
          if [ ${{ steps.strict_lint.outcome }} == 'success' ]; then
            gh pr review ${{ github.event.pull_request.number }} --comment --body "✅ **In-Depth Review Passed!** Everything looks great—\`black\`, \`isort\`, and \`flake8\` are all happy. Awesome work!"
          else
            # Step 1: Submit the helpful review requesting changes.
            gh pr review ${{ github.event.pull_request.number }} --request-changes --body "⚠️ **In-Depth Review Complete.** I found a few things that could be improved and left comments on the specific lines.

            **Remember, these are just suggestions and this PR is not blocked.**

            If you'd like me to fix the formatting automatically, just reply with a new comment:
            \`\`\`
            /format
            \`\`\`
            "
            
            # Step 2: Immediately submit a silent approval to unblock the PR.
            # Removing the body makes it truly silent in the timeline.
            gh pr review ${{ github.event.pull_request.number }} --approve
          fi
        env: { GH_TOKEN: "${{ secrets.APPROVER_TOKEN }}", GH_REPO: "${{ github.repository }}" }

      - name: "Cleanup: Remove Trigger Label"
        if: always()
        run: gh pr edit ${{ github.event.pull_request.number }} --remove-label "bot: in-depth review"
        env: { GH_TOKEN: "${{ secrets.APPROVER_TOKEN }}", GH_REPO: "${{ github.repository }}" }